name: Sphinx Docs

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: "Build and Deploy"
    runs-on: macos-latest
    env:
      CXX : clang++
      BUILD_CONFIG : >
        -G Ninja
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_PREFIX_PATH='/usr/local/opt/boost'
        -DSEQUANT_BUILD_DOCS=ON
    steps:
      - uses: actions/checkout@v4

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Install prerequisite MacOS packages
        run: brew install ninja boost catch2 && brew install --cask doxygen

      - name: Install prerequisite Python packages
        run: pip install -r doc/sphinx/requirements.txt

      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE $BUILD_CONFIG

      - name: Build Documentation
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: cmake --build . --target sphinx-sequant

      - name: Push Documentation to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        # if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        if: ${{ github.event_name == 'push'}}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{github.workspace}}/build/doc/sphinx/html
          force_orphan: false # the branch is published with only the latest commit
